### PR TITLE
Add `class` key to columns

### PR DESCRIPTION
**Pull request by ronen**
Includes test & documentation.

Implements #13

### CODE REVIEW

**Comment by crisward** [comment]
All looks good. Thanks!

**Comment by crisward** [comment]
Something has broke since 2ec91f779b28c857d4c50656b94b872a5755a796
Scrolling no longer working... any ideas?

**Comment by crisward** [comment]
see test/index.html locally to see what I mean

**Comment by crisward** [comment]
ok think I've found it, a couple of spacing issues in the jade bit. Weird non of the tests broke.

**Comment by ronen** [comment]
Oops sorry about the spacing.  My editor syntax settings don't recognize jade embedded in .tag so it was sometimes doing some weird inappropriate autoindent correction.  I thought I had caught those, must have slipped through.   

(In my own copy of this code that I had moved into the project I'm working on with it, I actually switched from jade to html since I don't have jade elsewhere in my pipeline.  Similarly that project isn't using coffeescript so I switched that to es6.  Hence the "backport" needed.)

**Pull request merged**
